# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [193]:
print(np.__version__)


1.16.5


#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
import numpy as np
a = np.zeros((10,))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [ ]:
array.size*array.itemsize


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [17]:
import numpy as np
np.add?


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
import numpy as np
a = np.zeros((10,))
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [38]:
import numpy as np
a = np.random.randint(10,49,size=(39,))
print(a)

[11 33 26 30 34 25 40 39 11 11 35 29 43 30 38 19 13 40 28 47 11 13 33 45
 21 26 38 22 27 11 34 36 18 32 33 15 28 47 44]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [35]:
import numpy as np
a=np.array([1,2,3,4,5])
a[::-1]

array([5, 4, 3, 2, 1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [197]:
import numpy as np
a=np.arange(0,9)
a.reshape(3,3)

                

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [21]:
import numpy as np
a = np.array([1,2,0,0,4,0])
for i in range(len(a)) :
    if a[i] != 0 :
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [5]:
import numpy as np
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [8]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.14550198 0.5042499  0.81520877]
  [0.54800203 0.5833525  0.83971818]
  [0.73925805 0.58052796 0.46924408]]

 [[0.64120554 0.36826153 0.86203851]
  [0.54403525 0.02698602 0.89985125]
  [0.27909167 0.363436   0.93000953]]

 [[0.97374747 0.2352696  0.29442073]
  [0.62920828 0.57277713 0.76561897]
  [0.74429686 0.07651036 0.45504322]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
import numpy as np
a = np.random.rand(10,10)
print("Min value is " , a.min())
print("Max value is " , a.max())


Min value is  0.002100482420520966
Max value is  0.9963101527585296


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [43]:
import numpy as np
a = np.random.random((30,))
print(np.mean(a))


0.5188282066055429


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [118]:
import numpy as np
a= np.ones((4,4))
a[1:-1,1:-1]=0




print(a)    

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [95]:
import numpy as np
a=np.ones((3,3))
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)
         

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [108]:
import numpy as np
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [192]:
import numpy as np
a=np.array([1,2,3,4])
b=np.random.rand(5,5)
np.diag(a)
#print(b)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [188]:
import numpy as np
a=np.ones((8,8))
a[::2,::2]=0
a[1::2,1::2]=0
print(a)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [150]:
import numpy as np
a = np.random.rand(6,7,8)
#b=np.size(a)
j=0
for i in a :
    j+=1
    if j == 99 :
        result=np.where(a == i)
print(result)    

(array([], dtype=int64),)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [186]:
import numpy as np
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)



In [93]:
import numpy as np
a = np.zeros((5,3))
b = np.ones((3,2))
c = a.dot(b)
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [210]:
import numpy as np
a = np.random.randint(2,12,size=(10,))
print(a)
for i in range (np.size(a)) :
    if a[i]>3 and a[i]<8 :
        a[i]=a[i]*(-1)
print(a)        


[4 6 3 2 5 2 3 9 2 9]
[-4 -6  3  2 -5  2  3  9  2  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [182]:
import numpy as np
a=np.random.randint(0,5,(3,3))
b=np.random.randint(0,7,(3,3))
c=[]
print(a)
print(b)
for i in a:
    print()
    #if i in b :
    #   c.append(i)
#print(c)    

[[3 4 2]
 [4 0 3]
 [4 1 2]]
[[5 4 4]
 [2 3 2]
 [2 1 5]]
4


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [174]:
import numpy as np
a = np.random.randint(0,10,(5,5))
print(a,'\n')
for i in range(5) :
    a[i,:]=np.random.randint(0,4,(5,))
print(a)    

[[9 6 9 9 1]
 [4 4 7 4 8]
 [9 9 9 9 7]
 [8 6 7 4 5]
 [0 6 0 2 9]] 

[[3 1 2 3 1]
 [0 3 0 1 2]
 [2 1 0 1 1]
 [3 0 3 1 1]
 [0 3 0 2 2]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [76]:
import numpy as np
a = np.linspace(0,1,10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [74]:
import numpy as np
a = np.random.rand(10)

print(np.sort(a))


[0.01255194 0.19398158 0.35778428 0.45856577 0.48352416 0.54891271
 0.70964372 0.81093003 0.87562949 0.87797075]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [165]:
import numpy as np
a = np.random.rand(3,2)
b = np.random.rand(2,3)
print(a)
print(b)
np.array_equal(a,b)

[[0.29579501 0.42227778]
 [0.03704778 0.26796836]
 [0.88663683 0.39150315]]
[[0.79464963 0.94486864 0.46212862]
 [0.66787147 0.43187991 0.83098863]]


False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [159]:
import numpy as np
a = np.random.rand(10,2)
#print(a)
x=a[:,0]
y=a[:,1]
l = list(zip(x,y))
r=np.sqrt(x**2 + y**2)
theta=np.arctan2(y,x)
q=list(zip(r,theta))
print(q)

[(0.9881912324528116, 0.9066276705528439), (0.8349744716027719, 1.4122393067215635), (0.7630069977685177, 1.0108474111788592), (0.43753599542859073, 0.38427576316136547), (1.081285797341814, 1.1400618606141237), (0.7822097944155418, 0.13885196846851633), (1.1060900511299716, 0.7109089947239907), (0.9117836733585503, 0.670559187667272), (0.8039765189820963, 0.752071012372511), (0.35080261726228096, 0.8481651520646459)]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [70]:
import numpy as np
a=np.random.rand(10)
#b = np.max(a)
print(a)
a[a==np.max(a)]=0
print(a)


[0.19575325 0.69574888 0.6536528  0.99858289 0.16941394 0.26657181
 0.8679656  0.61013488 0.97016864 0.82843421]
[0.19575325 0.69574888 0.6536528  0.         0.16941394 0.26657181
 0.8679656  0.61013488 0.97016864 0.82843421]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [107]:
import numpy as np
a = np.random.randint(1,15,size=(3,3))
#print(a)
for i in range(9) :
    print(a[i:i+1])

[[6 8 2]]
[[ 3  5 13]]
[[ 3 14  3]]
[]
[]
[]
[]
[]
[]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)